// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package game

import (
	"top-down-tdd/abstractions"
	"top-down-tdd/presenter"
	"top-down-tdd/user-input"
)

// Injectors from wire.go:

func MakeGame() (abstractions.Game, error) {
	inputHandler := userinput.NewTerminalUserInputHandler()
	abstractionsPresenter := presenter.NewTerminalPresenter()
	abstractionsGame := newGame(inputHandler, abstractionsPresenter)
	return abstractionsGame, nil
}
