// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package game

// Injectors from game-wire.go:

func InitializeGame() (Game, error) {
	game := NewGame()
	return game, nil
}
