// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package game

import (
	"top-down-tdd/abstractions"
	"top-down-tdd/user-input"
)

// Injectors from game-wire.go:

func InitializeGame() (abstractions.Game, error) {
	inputHandler := userinput.NewUserInput()
	abstractionsGame := NewGame(inputHandler)
	return abstractionsGame, nil
}
