// Code generated by MockGen. DO NOT EDIT.
// Source: top-down-tdd/abstractions (interfaces: Player)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPlayer is a mock of Player interface.
type MockPlayer struct {
	ctrl     *gomock.Controller
	recorder *MockPlayerMockRecorder
}

// MockPlayerMockRecorder is the mock recorder for MockPlayer.
type MockPlayerMockRecorder struct {
	mock *MockPlayer
}

// NewMockPlayer creates a new mock instance.
func NewMockPlayer(ctrl *gomock.Controller) *MockPlayer {
	mock := &MockPlayer{ctrl: ctrl}
	mock.recorder = &MockPlayerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlayer) EXPECT() *MockPlayerMockRecorder {
	return m.recorder
}

// GetMark mocks base method.
func (m *MockPlayer) GetMark() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMark")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetMark indicates an expected call of GetMark.
func (mr *MockPlayerMockRecorder) GetMark() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMark", reflect.TypeOf((*MockPlayer)(nil).GetMark))
}

// ShowName mocks base method.
func (m *MockPlayer) ShowName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShowName")
	ret0, _ := ret[0].(string)
	return ret0
}

// ShowName indicates an expected call of ShowName.
func (mr *MockPlayerMockRecorder) ShowName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowName", reflect.TypeOf((*MockPlayer)(nil).ShowName))
}
