// Code generated by MockGen. DO NOT EDIT.
// Source: game.go

// Package mock_abstractions is a generated GoMock package.
package mock_abstractions

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGame is a mock of Game interface.
type MockGame struct {
	ctrl     *gomock.Controller
	recorder *MockGameMockRecorder
}

// MockGameMockRecorder is the mock recorder for MockGame.
type MockGameMockRecorder struct {
	mock *MockGame
}

// NewMockGame creates a new mock instance.
func NewMockGame(ctrl *gomock.Controller) *MockGame {
	mock := &MockGame{ctrl: ctrl}
	mock.recorder = &MockGameMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGame) EXPECT() *MockGameMockRecorder {
	return m.recorder
}

// InitGame mocks base method.
func (m *MockGame) InitGame() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitGame")
	ret0, _ := ret[0].(int)
	return ret0
}

// InitGame indicates an expected call of InitGame.
func (mr *MockGameMockRecorder) InitGame() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitGame", reflect.TypeOf((*MockGame)(nil).InitGame))
}
